tasks:
  - init: >
      sudo apt-get update &&
      sudo apt-get install -y mysql-server &&
      sudo mysql_secure_installation &&
      sudo service mysql start
  - command: >
      mysql -u root -e "CREATE USER 'root'@'localhost' IDENTIFIED BY '210922MX';" &&
      mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'gitpod'@'localhost';" &&
      mysql -u root -e "FLUSH PRIVILEGES;"

ports:
  - port: 3306
    onOpen: open-preview
